# Generated by Django 5.1 on 2024-09-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
